name:
  cassandra-demo
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9041:9042"
    networks:
      - database-tier
    volumes:
      - cassandra1-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
    healthcheck:
      test: [ "CMD","cqlsh" ]
      interval: 30s
      timeout: 10s
      retries: 5




  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9042:9042"
    networks:
      - database-tier
    volumes:
      - cassandra1-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
    depends_on:
      cassandra1:
        condition: service_healthy





volumes:
  cassandra1-data:
  cassandra2-data:

networks:
  database-tier: { }
